# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Node

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-node:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ServerProject-DONT-IMPORT-INTO-UNITY
    - name: Build
      run: dotnet build --no-restore
      working-directory: ServerProject-DONT-IMPORT-INTO-UNITY
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ServerProject-DONT-IMPORT-INTO-UNITY
    - name: Upload LRM
      uses: actions/upload-artifact@v3
      with:
        name: LRM-Node
        path: |
          ServerProject-DONT-IMPORT-INTO-UNITY/MultiCompiled/bin/Debug/net5.0/LRM.dll
          ServerProject-DONT-IMPORT-INTO-UNITY/MultiCompiled/bin/Debug/net5.0/LRM.runtimeconfig.json
          ServerProject-DONT-IMPORT-INTO-UNITY/MultiCompiled/bin/Debug/net5.0/MultiCompiled.dll
          
